name: Day 1 CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Build started"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Running tests"

  secret-demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ secrets.MY_NAME }}"


